services:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    image: docker.io/bitnami/mariadb:11.3.2
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=prestashop_db
      - MARIADB_USER=prestashop_user
      - MARIADB_PASSWORD=db_password
    volumes:
      - /home/user/bitnami/mariadb:/bitnami/mariadb
    networks:
      - prestashop-net

  prestashop:
    container_name: prestashop
    restart: unless-stopped
    image: docker.io/bitnami/prestashop:8.1.7
    links:
      - mariadb
    depends_on:
      - mariadb    
    environment:
      - PRESTASHOP_HOST=example.com or 192.168.0.2 # Need to mod this for your ip    
      - PRESTASHOP_ENABLE_HTTPS=yes      
      - PRESTASHOP_TIMEZONE=UTC
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=prestashop_user
      - PRESTASHOP_DATABASE_NAME=prestashop_db
      - PRESTASHOP_DATABASE_PASSWORD=db_password
      - PRESTASHOP_FIRST_NAME=FirstName
      - PRESTASHOP_LAST_NAME=LastName
      - PS_DEV_MODE=0
      - PS_DEMO_MODE=0
      - PS_FOLDER_ADMIN=admin_folder
      - PRESTASHOP_PASSWORD=admin_password
      - PRESTASHOP_EMAIL=admin@example.com
      - PHP_UPLOAD_MAX_FILESIZE=0M
      - PHP_MEMORY_LIMIT=512M
      - ALLOW_EMPTY_PASSWORD=no
      - PRESTASHOP_SMTP_HOST=smtp.example.com
      - PRESTASHOP_SMTP_PORT=587
      - PRESTASHOP_SMTP_USER=smtp_user
      - PRESTASHOP_SMTP_PASSWORD=smtp_password
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prestashop.entrypoints=websecure"
      - "traefik.http.routers.prestashop.tls.certresolver=myresolver"

      # Middleware and router for redirecting www to non-www
      - "traefik.http.routers.prestashop.rule=Host(`example.com`) || Host(`www.example.com`)"
      - "traefik.http.middlewares.prestashop-redirect.redirectregex.regex=^(https?://)www.(.*)$$"
      - "traefik.http.middlewares.prestashop-redirect.redirectregex.replacement=$${1}$${2}"
      - "traefik.http.routers.prestashop.middlewares=prestashop-redirect"

      # Middleware and router for redirecting example.com to https://example.com
      - "traefik.http.middlewares.example-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.example-redirect.rule=Host(`example.com`)"
      - "traefik.http.routers.example-redirect.entrypoints=websecure"
      - "traefik.http.routers.example-redirect.middlewares=example-redirect"
      - "traefik.docker.network=web"

    volumes:
      - /home/user/bitnami/prestashop:/bitnami/prestashop
    networks:      
      - web
      - prestashop-net

  phpmyadmin:
    container_name: myphpadmin
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"

      # Middleware and router for redirecting www to non-www
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.example.com`) || Host(`www.phpmyadmin.example.com`)"
      - "traefik.http.middlewares.phpmyadmin-redirect.redirectregex.regex=^(https?://)www.(.*)$$"
      - "traefik.http.middlewares.phpmyadmin-redirect.redirectregex.replacement=$${1}$${2}"
      - "traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-redirect"

      # Middleware and router for redirecting phpmyadmin.example.com to https://phpmyadmin.example.com
      - "traefik.http.middlewares.phpmyadmin-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.phpmyadmin-redirect.rule=Host(`phpmyadmin.example.com`)"
      - "traefik.http.routers.phpmyadmin-redirect.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin-redirect.middlewares=phpmyadmin-redirect"
      - "traefik.docker.network=web"

    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:      
      - web
      - prestashop-net

networks:
  web:
    external: true
  prestashop-net:
    external: true  

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
